### ISSUE TITLE
qrcode app does not work with rocket.chat 2.4

### ISSUE THREAD

**Issue by elurex** [wreiske/Rocket.Chat.App-QRCode#1]
qrcode app does not work with rocket.chat 2.4

```
debug: 2020-01-10T08:22:26.788Z (Caller: anonymous OR constructor)

[
  "qrcode's executor is being executed...",
  {
    "sender": {
      "id": "S8D6qqmwRtiB9GXfP",
      "username": "elurex",
      "emails": [
        {
          "address": "user@email.net",
          "verified": true
        }
      ],
      "type": 0,
      "isEnabled": true,
      "name": "Administrator",
      "roles": [
        "admin"
      ],
      "status": "online",
      "statusConnection": "online",
      "utcOffset": 8,
      "createdAt": "2019-12-09T07:39:45.128Z",
      "updatedAt": "2020-01-10T08:16:06.258Z",
      "lastLoginAt": "2020-01-10T07:08:50.916Z"
    },
    "room": {
      "id": "GENERAL",
      "slugifiedName": "general",
      "type": "c",
      "isDefault": true,
      "isReadOnly": false,
      "displaySystemMessages": true,
      "messageCount": 591,
      "createdAt": "2019-12-09T07:36:36.346Z",
      "updatedAt": "2019-12-14T10:00:30.058Z",
      "lastModifiedAt": "2019-12-10T16:48:17.744Z"
    },
    "params": [
      "https://www.google.com"
    ]
  }
]

error: 2020-01-10T08:22:26.797Z (Caller: anonymous OR constructor)

[
  "{\"stack\":\"TypeError: Cannot read property '_id' of undefined
    at Promise.asyncApply (app/apps/server/bridges/messages.js:22:14)
    at /opt/Rocket.Chat-2.4.0/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Cannot read property '_id' of undefined\"}"
]

debug: 2020-01-10T08:22:26.797Z (Caller: anonymous OR constructor)

[
  "qrcode's executor was unsuccessful."
]
```

**Comment by wreiske** [comment]
All rocket chat apps are having this issue at the moment. They are working on a fix. Please see https://github.com/RocketChat/Rocket.Chat/issues/16187

Thanks!

**Comment by wreiske** [comment]
Please upgrade your rocket.chat to https://github.com/RocketChat/Rocket.Chat/releases/tag/2.4.1

Let me know if you have any other issues! Thanks.
