### ISSUE TITLE
Not enough permission

### ISSUE THREAD

**Issue by iBelow** [wreiske/Rocket.Chat.App-QRCode#2]
Errors 
![image](https://user-images.githubusercontent.com/8112733/142633374-f9f7cb82-0e3a-45ef-ac69-9e0aec596312.png)

what permissions do I need to work?

```

  "qrcode's executor is being executed...",
  {
    "sender": {
      "id": "TZxzRc5MHtLP37Swc",
      "username": "username",
      "emails": [
        {
          "address": "EMAIL",
          "verified": true
        }
      ],
      "type": "user",
      "isEnabled": true,
      "name": "NAME",
      "roles": [
        "user",
        "admin"
      ],
      "status": "online",
      "statusConnection": "online",
      "utcOffset": 3,
      "createdAt": "2021-11-02T20:59:16.447Z",
      "updatedAt": "2021-11-19T13:41:19.413Z",
      "lastLoginAt": "2021-11-19T13:11:22.464Z"
    },
    "room": {
      "id": "GENERAL",
      "slugifiedName": "general",
      "type": "c",
      "isDefault": true,
      "isReadOnly": false,
      "displaySystemMessages": true,
      "messageCount": 9,
      "createdAt": "2021-11-02T20:58:47.332Z",
      "updatedAt": "2021-11-19T13:45:08.682Z",
      "lastModifiedAt": "2021-11-19T13:45:08.609Z"
    },
    "params": [
      "https://rocketbooster.net"
    ],
    "triggerId": "AXC7EfFQ72zvP3bCJ"
  }
]
```

```


[
  "{\"stack\":\"Error: Not enough permission\\n    at validateMessage (app/lib/server/functions/sendMessage.js:151:10)\\n    at sendMessage (app/lib/server/functions/sendMessage.js:165:2)\\n    at executeSendMessage (app/lib/server/methods/sendMessage.js:79:10)\\n    at app/apps/server/bridges/messages.ts:25:23\\n    at /snap/rocketchat-server/1491/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Not enough permission\"}"
]
```

rocket chat versions: 3.18.3

**Comment by brtptrs** [comment]
We are seeing the same error on Version 4.2.0

**Comment by njeudy** [comment]
think you have to add group "app" on your user in rocket.chat

**Comment by chr-di** [comment]
is there another way to enable normal users to use the /qrcode command other than assigning the app role to them?
